from __future__ import annotations

import argparse
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import torch
from datasets import Dataset
from dotenv import load_dotenv
from peft import LoraConfig, TaskType, get_peft_model
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments,
)


BASE_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = BASE_DIR.parent
load_dotenv(PROJECT_ROOT / ".env", override=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train a local LoRA adapter from JSONL chat data.")
    parser.add_argument(
        "--dataset",
        default=os.getenv("LLM_TRAIN_OUTPUT_PATH", str(BASE_DIR / "artifacts" / "aapl_llm_finetune.jsonl")),
        help="Path to JSONL dataset generated by prepare_llm_training_data.py",
    )
    parser.add_argument(
        "--base-model",
        default=os.getenv("LORA_BASE_MODEL", "Qwen/Qwen2.5-0.5B-Instruct"),
        help="Hugging Face base model to adapt.",
    )
    parser.add_argument(
        "--output-dir",
        default=str(BASE_DIR / "artifacts" / "lora_runs"),
        help="Directory where adapter outputs will be saved.",
    )
    parser.add_argument("--sample-size", type=int, default=1024, help="Use only the latest N samples (0 = all).")
    parser.add_argument("--max-seq-len", type=int, default=1024, help="Max sequence length for tokenization.")
    parser.add_argument("--batch-size", type=int, default=1, help="Per-device train batch size.")
    parser.add_argument("--grad-accum", type=int, default=8, help="Gradient accumulation steps.")
    parser.add_argument("--max-steps", type=int, default=20, help="Max training steps for this run.")
    parser.add_argument("--lr", type=float, default=2e-4, help="Learning rate.")
    parser.add_argument("--lora-r", type=int, default=16, help="LoRA rank.")
    parser.add_argument("--lora-alpha", type=int, default=32, help="LoRA alpha.")
    parser.add_argument("--lora-dropout", type=float, default=0.05, help="LoRA dropout.")
    parser.add_argument("--use-4bit", action="store_true", help="Enable QLoRA 4-bit quantization if available.")
    parser.add_argument("--dry-run", action="store_true", help="Validate data/model pipeline without training.")
    return parser.parse_args()


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        raise FileNotFoundError(f"Dataset not found: {path}")
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    if not rows:
        raise ValueError("Dataset is empty.")
    return rows


def to_chat_text(example: dict[str, Any], tokenizer: AutoTokenizer) -> str:
    messages = example.get("messages", [])
    if hasattr(tokenizer, "apply_chat_template"):
        try:
            return tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)
        except Exception:
            pass
    chunks: list[str] = []
    for msg in messages:
        role = str(msg.get("role", "user")).upper()
        content = str(msg.get("content", ""))
        chunks.append(f"{role}: {content}")
    return "\n".join(chunks)


def collect_target_modules(model: AutoModelForCausalLM) -> list[str]:
    preferred_suffixes = [
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ]
    found: list[str] = []
    for name, _ in model.named_modules():
        leaf = name.split(".")[-1]
        if leaf in preferred_suffixes and leaf not in found:
            found.append(leaf)
    if found:
        return found

    fallback: list[str] = []
    for name, module in model.named_modules():
        leaf = name.split(".")[-1]
        if isinstance(module, torch.nn.Linear) and leaf != "lm_head" and leaf not in fallback:
            fallback.append(leaf)
    if not fallback:
        raise RuntimeError("Could not infer LoRA target modules from model.")
    return fallback


def build_model_and_tokenizer(args: argparse.Namespace):
    use_cuda = torch.cuda.is_available()
    dtype = torch.float16 if use_cuda else torch.float32
    quant_config = None

    if args.use_4bit:
        try:
            quant_config = BitsAndBytesConfig(
                load_in_4bit=True,
                bnb_4bit_quant_type="nf4",
                bnb_4bit_compute_dtype=torch.float16 if use_cuda else torch.float32,
                bnb_4bit_use_double_quant=True,
            )
        except Exception as exc:
            raise RuntimeError(
                "--use-4bit requested, but bitsandbytes setup failed. Install bitsandbytes or remove --use-4bit."
            ) from exc

    tokenizer = AutoTokenizer.from_pretrained(args.base_model, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        args.base_model,
        trust_remote_code=True,
        torch_dtype=dtype,
        device_map="auto" if use_cuda else None,
        quantization_config=quant_config,
    )
    model.config.use_cache = False

    target_modules = collect_target_modules(model)
    lora_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        inference_mode=False,
        r=args.lora_r,
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
        target_modules=target_modules,
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()
    return model, tokenizer, target_modules


def tokenize_dataset(dataset: Dataset, tokenizer: AutoTokenizer, max_seq_len: int) -> Dataset:
    def _map_fn(batch: dict[str, list[str]]) -> dict[str, Any]:
        tokens = tokenizer(
            batch["text"],
            truncation=True,
            max_length=max_seq_len,
            padding=False,
        )
        tokens["labels"] = tokens["input_ids"].copy()
        return tokens

    return dataset.map(_map_fn, batched=True, remove_columns=dataset.column_names)


def main() -> None:
    args = parse_args()
    dataset_path = Path(args.dataset)
    output_root = Path(args.output_dir)
    run_name = f"lora_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}"
    output_dir = output_root / run_name
    output_dir.mkdir(parents=True, exist_ok=True)

    raw_rows = load_jsonl(dataset_path)
    if args.sample_size > 0:
        raw_rows = raw_rows[-args.sample_size :]

    model, tokenizer, target_modules = build_model_and_tokenizer(args)
    texts = [to_chat_text(item, tokenizer) for item in raw_rows]

    if args.dry_run:
        sample = texts[0]
        encoded = tokenizer(sample, truncation=True, max_length=args.max_seq_len)
        print("Dry run OK")
        print(f"Dataset rows: {len(texts)}")
        print(f"Sample token count: {len(encoded['input_ids'])}")
        print(f"LoRA target modules: {target_modules}")
        print(f"Base model: {args.base_model}")
        return

    hf_dataset = Dataset.from_dict({"text": texts})
    tokenized = tokenize_dataset(hf_dataset, tokenizer, args.max_seq_len)

    use_cuda = torch.cuda.is_available()
    training_args = TrainingArguments(
        output_dir=str(output_dir),
        per_device_train_batch_size=args.batch_size,
        gradient_accumulation_steps=args.grad_accum,
        learning_rate=args.lr,
        max_steps=args.max_steps,
        warmup_steps=max(1, int(args.max_steps * 0.1)),
        logging_steps=max(1, min(10, args.max_steps)),
        save_steps=args.max_steps,
        save_total_limit=1,
        bf16=False,
        fp16=use_cuda,
        optim="adamw_torch",
        report_to="none",
    )

    collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized,
        data_collator=collator,
    )

    trainer.train()
    model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)

    metadata = {
        "base_model": args.base_model,
        "dataset": str(dataset_path),
        "rows_used": len(texts),
        "max_steps": args.max_steps,
        "max_seq_len": args.max_seq_len,
        "target_modules": target_modules,
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
    }
    with (output_dir / "run_metadata.json").open("w", encoding="utf-8") as handle:
        json.dump(metadata, handle, indent=2)

    print("LoRA training complete")
    print(f"Adapter dir: {output_dir}")
    print(f"Rows used: {len(texts)}")
    print(f"Base model: {args.base_model}")


if __name__ == "__main__":
    main()
